# length of the axis in voxel space in meters
x_range : [0.0,0.3]
y_range : [0.0,0.3]
z_range : [0.0,0.3]

# voxel size of each axis in meters.
voxel_size : [0.0075,0.0075,0.0075]

# Camera intrinsic parameters. 3×3 matrix
K : [[540, 0.0, 320],
     [0.0, 540, 240],
     [0.0, 0.0, 1.0]]

focal_length : 0.00188

# number of input images
num_images : 1

# extrinsic of each image. 3×4 matrix
extrinsic1 : [[ 1.,          0.        ,  0.        ,  0.15      ],
              [-0.,         -0.87789557,  0.47885213, -0.15      ],
              [-0.,         -0.47885213, -0.87789557,  0.6       ],
              [ 0.,          0.        ,  0.        ,  1.        ]]








